// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface PageHome {
  headline: string;
  role: string;
  hero_intro: StoryblokRichtext;
  about_intro: StoryblokRichtext;
  profile_image?: StoryblokAsset;
  roles: (
    | "Angular"
    | "Design Systems"
    | "Frontend Architecture"
    | "Monorepo"
    | "Next.js"
    | "React"
    | "Redux"
    | "Responsive UI"
    | "RxJS"
    | "SSR / SSG / ISR"
    | "State Management"
    | "Storyblok"
    | "TypeScript"
    | "Vercel"
  )[];
  availability_note: string;
  availability_status: string;
  availability_timezone: string;
  availability_response_time: string;
  social_links: ItemSocialLink[];
  featured_projects: (ISbStoryData<PageProject> | string)[];
  experience: (ISbStoryData<ItemExperience> | string)[];
  seo: SeoMeta[];
  component: "page_home";
  _uid: string;
}

export interface PageProject {
  title: string;
  slug: string;
  summary: string;
  content?: StoryblokRichtext;
  published_date: string;
  project_url?: string;
  repository_url?: string;
  type: string;
  portfolio_priority?: string;
  stack?: (
    | "AI"
    | "Agentic Workflow"
    | "Angular"
    | "Atomic Design"
    | "B2B Workflows"
    | "BoardGame.io"
    | "C#"
    | "Calendar UI"
    | "Calendar UX"
    | "Civic Tech"
    | "Context API"
    | "Cypress"
    | "Docker Review Apps"
    | "Enterprise UI"
    | "Fintech UI"
    | "Game Systems"
    | "GraphQL Codegen"
    | "ISR"
    | "Interactive UI"
    | "Internal Tools"
    | "Monte Carlo Tree Search"
    | "Multi-brand CMS"
    | "Multiplayer Flows"
    | "Next.js"
    | "Next.js App Router"
    | "Next.js Pages Router"
    | "Node.js"
    | "Platform Architecture"
    | "React"
    | "Redux"
    | "Responsive UI"
    | "RxJS"
    | "Sass"
    | "State Management"
    | "Static Deployment"
    | "Storyblok"
    | "Tailwind CSS"
    | "Turborepo"
    | "TypeScript"
    | "URQL"
    | "Vercel"
    | "Vitest"
    | "XLSX Parser"
    | "redux-observable"
  )[];
  logo?: StoryblokAsset;
  seo: SeoMeta[];
  component: "page_project";
  _uid: string;
}

export interface PageWriting {
  title: string;
  slug: string;
  excerpt: string;
  content: StoryblokRichtext;
  published_date: string;
  cover_image?: StoryblokAsset;
  tags?: (number | string)[];
  seo: SeoMeta[];
  component: "page_writing";
  _uid: string;
}

export interface ItemExperience {
  title: string;
  company_name: string;
  description: StoryblokRichtext;
  start_date: string;
  end_date?: string;
  skills: (
    | "AWS"
    | "Angular"
    | "Bitcoinjs-lib"
    | "Cypress"
    | "Git"
    | "GraphQL Codegen"
    | "Next.js"
    | "Next.js Pages Router"
    | "Platform Architecture"
    | "React"
    | "Redux"
    | "RxJS"
    | "SVN"
    | "Sass"
    | "Tailwind CSS"
    | "TypeScript"
    | "Typescript"
    | "URQL"
    | "Vercel"
    | "Vitest"
  )[];
  image?: StoryblokAsset;
  component: "item_experience";
  _uid: string;
}

export interface ItemSocialLink {
  name: string;
  url: string;
  icon: string;
  component: "item_social_link";
  _uid: string;
}

export interface SeoMeta {
  meta_title: string;
  meta_description: string;
  canonical_url?: string;
  og_image?: StoryblokAsset;
  noindex?: boolean;
  component: "seo_meta";
  _uid: string;
}

export type ContentType = PageHome | PageProject | PageWriting | ItemExperience;
